#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
    path: /register
    controller: App\Controller\AuthenticatorController::register
    methods: POST

api:
    path: /api
    controller: App\Controller\AuthenticatorController::api

login_check:
    path:     /login_check
    methods:  [POST]

get_user:
    path:     /api/pro
    controller: App\Controller\AuthenticatorController::getCompleteUser
    methods:  [GET]

#add_car:
#    path: /api/cars/add_car
#    controller: App\Controller\CarController::addCar
#    methods: [POST]
